version: 1.0.{build}

build_script:
- ps: |
    $PSVersionTable
    $pwd
    Get-InstalledModule Pester
    Install-Module Pester -Scope CurrentUser -Force
    Get-InstalledModule Pester
    Invoke-Pester .\Tests -EnableExit